### ISSUE TITLE
Borken

### ISSUE THREAD

**Issue by mew351** [catbergcheats/catpaste#1]
Did you remove your resolver/ragebot?

**Comment by catbergcheats** [comment]
I did, I just need to also fix all of the compile errors when it is calling the resolver/ragebot, currently I am trying to debug.

**Comment by mew351** [comment]
Do you have a Discord?
Mind sharing the files?
Do you have updated offsets aswell?

**Comment by catbergcheats** [comment]
Yes I have a discord. check discord.gg/uKWnph
